### ISSUE TITLE
Documentation issue - Win2016 R2 platform

### ISSUE THREAD

**Issue by NZainchkovskiy** [SubPointSolutions/metabox#1]
Do you have a type in documentation, or Win2016 platform will be really support only Win2016 R2 version?  As far as I know Win2016 R2 wasn't released yet.

**Comment by avishnyakov** [comment]
Once it's there, we'll give it a go. From what we see, it is a matter of Packer/Vagrant working well with this platform, and then putting together correct PowerShell/DSC scripts to ensure and validate the right setup.

We don't depend on a particular platform at all, a matter of Vagrant/Packer supporting these. We only automated on top of these tools :)

**Comment by shurick81** [comment]
Yes, thanks @NZainchkovskiy, It must be a typo. First, we implement 2016 stack based on Win 2016 and only further on the plan is to support Win 2016 R2.
