### ISSUE TITLE
Add SP 2013 trial product key

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#27]
As a DevOps I need a quicker procedure of adopting Metabox to particular project and It would be great to have trial SP 2013 key preset in MB documents.

**Comment by avishnyakov** [comment]
@shurick81 we ship SharePoint 2013 RTM with a trial key on win2012 stack. With the 2012-r2 stack, hover, we do SP2013 SP1 which goes only via downloading MSDN image and then adding your own key.

I guess there are a few things we could do here, not sure which one you'd like to see:
* implement SharePoint 2013 RTM with win2012-r2 stack (which would be pretty useless)
* add trial key by default for SP2013 SP1 (which needs to be tested)

Could you please elaborate more on your view so we can move it forward?

**Comment by shurick81** [comment]
Yes, it works with this one, I just tested. Here goes the PR: https://github.com/SubPointSolutions/metabox/pull/67

**Comment by SubPointSupport** [comment]
Done, thanks @shurick81, closing this one.
