### ISSUE TITLE
Errors while installing vagrant (Chocolatey)

### ISSUE THREAD

**Issue by NZainchkovskiy** [SubPointSolutions/metabox#28]
I'm trying to complete "Getting started guide". 
Now I'm stack on provision of prerequisites.
After executing `powershell .\bootstrap-windows.ps1 --provision` command I'm getting this error: 

> ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\sp_farm\AppData\Local\Temp\chocolatey\vagrant\2.0.1\vagrant_2.0.1_x86_64.msi" /qn /norestart ] was not successful. Exit code was '1603'. See log for possible error messages.
The install of vagrant was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\vagrant\tools\chocolateyinstall.ps1'.
 See log for details.

> Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

>Failures
 >- vagrant (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\vagrant\tools\chocolateyinstall.ps1'.
 See log for details.
Exiting with non-zero code [1603] - Failed to install vagrant
Exiting with non-zero code [1603] - Failed to install vagrant
At C:\Metabox\metabox\src\bootstrap-windows.ps1:32 char:9
>+         throw "Exiting with non-zero code [$code] - $message"
>+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : OperationStopped: (Exiting with no...install vagrant:String) [], RuntimeException
 >   + FullyQualifiedErrorId : Exiting with non-zero code [1603] - Failed to install vagrant

I'm on Windows 2016 Server.
What I am doing wrong?
I can attach log file if it will help.

**Comment by shurick81** [comment]
Hi @NZainchkovskiy, thanks for your feedback. Did you run the console with admin permissions?

**Comment by shurick81** [comment]
Yes, put the log in gist and provide a link in a comment here.

**Comment by NZainchkovskiy** [comment]
I run the console with admin permissions.
Log file can be found here: https://gist.github.com/NZainchkovskiy/37c4f473ecbf7f8e958f8ad629edf590

**Comment by avishnyakov** [comment]
Just wondering, could you please try `choco install -y vagrant` or just install it from the official distro?
> https://www.vagrantup.com/downloads.html

Really sorry about this, but these are 3rd part tools which we won't have much control over. As for the win2016, we have been running it on both laptops, PC and cloud-based win2016 installs without issues.

**Comment by avishnyakov** [comment]
@NZainchkovskiy , 1603 error code, is that the one?
> http://www.hurryupandwait.io/blog/more-windows-packaging-for-vagrant-and-fixing-1603-errors-during-msi-installs

**Comment by NZainchkovskiy** [comment]
@avishnyakov manual installation did the trick, now I have all green when running provision script. I still don't know what was wrong with powershell installation.

**Comment by avishnyakov** [comment]
Closing, @NZainchkovskiy
