### ISSUE TITLE
Optimize CLI usage and usability

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#32]
As a metabox user, I want to consume metabox via clean CLI commands without worrying about tons of details or editing config files.

There are a few things to consider for this:

* [ ] auto-sourcing of config files, moving away from bash/sh 
* [ ] eliminate all default ENV variables from config files, config should have data for YAML documents only
* [ ] introduce --log-level and --branch-name flags, there are most used, they should not be in config files

The end goal to simplify CLI usage, eliminate common parameters which we don't have to specify in config files and move them into CLI itself, get away from bash/sh (too much hassle to support across platforms) to YAML files (similar to databags in Chef), avoid editing config files for metabox-related switched (log level and branch name).

It's a pretty important to implement. Current config management isn't scalable between platforms, cluttered and unfriendly.

**Comment by SubPointSupport** [comment]
Closing, this is done with metabox cli usage:
> https://github.com/SubPointSolutions/metabox/issues/86#issuecomment-398462556
