### ISSUE TITLE
Support SharePoint 2013/16 prerequisites install

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#35]
As a metabox user, I want to have an offline installation of SharePoint binaries.

Currently, metabox goes online to get these prereqs installed. That could be improved, we should consider using offline prereqs installation.

We had a quick run over this, implemented file resources to download all required files. However, we couldn't get a consistent behaviour for SP2013/SP2013 SP1 and SP2016. SharePoint DSC would report a success but further SharePoint farm creation would raise an exception referring to incorrect prereq install. Haven't had much time to look into details, hence switched to online installs.

More of a nice-to-have feature which we should implement later on. Help really wanted on this one.

**Comment by shurick81** [comment]
again we can consider using this: https://github.com/brianlala/AutoSPSourceBuilder

**Comment by avishnyakov** [comment]
Low priority, closing for the time being. We'll use "Other images/boxes for metabox #7" for the future reference.
