### ISSUE TITLE
Make jdk-8u141-linux-x64.tar.gz offline install

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#40]
As a metabox user, I want to have Java8 installed from offline source for our Linux images.

Java install takes ~200 Mb for every `centos7-mb-java8` box which is required by metabox CI.
File resource and then Linux file transfer similar to windows needs to be used.

A thing to consider is that windows has got PowerShell with super-reach functionality, and Linux has `bash` which would be much harder to use. We can consider configuration management tool or just:
* use Ruby or Python
* use PowerShell under Linux if it supports REST queries and so on (so it's would be nearly the same port)

While we don't really have to do this right now, it slows down CI box re-build and wastes ~200Mb every time we re-build java8 image for CI server. It's okay for online CI but rather undesired for local installations on laptops and local regression testing.

**Comment by SubPointSupport** [comment]
Won't work on this. Moving towards Docker-ized Jenkins2 setup within a light linux box. No need to get Java8 installed and go with a heavy Packer/Vagrant workflow.
