### ISSUE TITLE
Support SharePoint 2013/2016 images with CU/SP

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#49]
As a metabox user, I want to be able to build and use SharePoint 2013/2016 images with pre-installed CU/SP.

As CI/CD matures, we should be able to streamline install and testing for SharePoint bin images on a giving CU/SP.

A follow up on "Other images/boxes for metabox #7"

**Comment by shurick81** [comment]
Here's probably the best data for CUs: https://github.com/brianlala/AutoSPSourceBuilder/blob/master/AutoSPSourceBuilder.xml
We need to think about using the whole AutoSPSourceBuilder for preparing SP and OOS medias. It is also connected to the whole idea of preparing the file resources so let's look at this in #42 and #43 too?

**Comment by avishnyakov** [comment]
Low priority, closing for the time being. We'll use "Other images/boxes for metabox #7" for the future reference.
