### ISSUE TITLE
Support Office Online Server (Office Web Apps server)

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#5]
As a metabox user, I want to be able to deploy SharePoint Farms with Office Online Server.

Downloading the file resource is going to be done in the same way as SP 2013 + SP1 because there is no public installation files for OOS.

A follow up on "Other images/boxes for metabox #7"

**Comment by avishnyakov** [comment]
Low priority, closing for the time being. We'll use "Other images/boxes for metabox #7" for the future reference.
