### ISSUE TITLE
Unstable dependency on PowerShell modules

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#56]
As a SP devops I need a more stable infrastructure provisioning flow, which means that dependency versions should be strictly specified. Currently only PowerShell module names are specified:
1. when installing modules
2. when referring (using) modules

**Comment by shurick81** [comment]
Now SharePointDsc 2.1 has been released by the way

**Comment by avishnyakov** [comment]
@shurick81 updated `_install-dsc-modules.ps1`, we still on SharePoint DSC 1.9.0.0 for the time being. Will test it with  2.1 some time from now.
