### ISSUE TITLE
Installing Language Packs

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#57]
As a SharePoint developer i need a dev infrastructure which is similar to production in terms language packs installed. The most important is to have language packs for those products that have UI: SharePoint and Office Online Server. This issue is connected to #7 , because it should be implemented by creating new images. Here is the link to an example of installing language packs via DSC: https://github.com/shurick81/SPConfStructor/blob/master/SharePointOnPrem/DSC/SPInstall.ps1. URLs for the language packs can be found here: https://github.com/brianlala/AutoSPSourceBuilder/blob/master/AutoSPSourceBuilder.xml.

**Comment by avishnyakov** [comment]
Low priority, closing for the time being. We'll use "Other images/boxes for metabox #7" for the future reference.
