### ISSUE TITLE
SharePoint 2016 FP2 image requires psconfig.exe run

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#60]
With the recent support for SharePoint 2016 Feature Pack 2 packer image, we install feature pack manually, as MSI/EXE, without using PowerShell DSC. 

Apparently, a manual run of psconfig.exe is required to finish off upgrade once the SharePoint farm is created:
```
cd "C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\BIN"
psconfig.exe -cmd upgrade -inplace b2b -force -cmd applicationcontent -install -cmd installfeatures

```

Overwise, we are seeing the following issue in some cases, especially while running SPMeta2 regression against SharePoint 2016 farm:

> SPMeta2.Exceptions.SPMeta2ModelDeploymentException: There was an error while provisioning definition. Check ModelNode prop. ---> Microsoft.SharePoint.Upgrade.SPUpgradeCompatibilityException: There is a compatibility range mismatch between the Web server and database "SPMeta2_Regression_Content_31442", and connections to the data have been blocked to due to this incompatibility. This can happen when a content database has not been upgraded to be within the compatibility range of the Web server, or if the database has been upgraded to a higher level than the web server. The Web server and the database must be upgraded to the same version and build level to return to compatibility range.

SharePoint DSC, most likely, run it internally, and we don't yet. Some solution can be found here:
> https://social.technet.microsoft.com/Forums/en-US/94c5f178-f020-4d0f-ba7c-11c415d0d862/manually-running-psconfig-is-required-after-installing-sharepoint-foundation-2010-updates?forum=smallbusinessserver

**Comment by shurick81** [comment]
Actually there is psconfig implemented as a DSC resource. I encountered that it fails sometime but it can be that it's just an SP failure, not DSC.
