### ISSUE TITLE
Fresh install of OfficeToolsForVS2015 hangs box

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#62]
Fresh installation of OfficeToolsForVS2015 on win2016 platform hangs the box:

```
webpicmd /Install /Products:OfficeToolsForVS2015 /AcceptEula
```
The box produces an endless log of "waiting" dots:
```
    win-2016-dev-local-1:  ..
    win-2016-dev-local-1:  ...
    win-2016-dev-local-1:  .
    win-2016-dev-local-1:  ..
    win-2016-dev-local-1:  ...
    win-2016-dev-local-1:  .
    win-2016-dev-local-1:  ..

```

Reboot helps but it indicated a hidden problem with a fresh install - pending reboot, license confirmation or something like this. Needs to be investigated as it break CI/CD testing.

**Comment by SubPointSupport** [comment]
Won't fix. Moving towards VS2017 install. Closing this ticket.
