### ISSUE TITLE
Consider rewriting bootstrap and CI agent scripts in Ruby

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/metabox#79]
Currently we have inconsistency with bootstrap and CI management scripts:

* bootstrap-windows.ps1 (windows, powershell)
* bootstrap-max.sh(macos, shell script)
* metabox-ci.ps1 (windows/mac, powershell)

These are initial prototypes made to support mac/windows platforms. That said, there is inconsistency, too much effort to support PowerShell/SH scripting working on two platforms. Besides, PowerShell needs to be installed on macos.

It might be a good idea to rewrite these scripts in plain ruby. That would make metabox initial dependency limited to Ruby, provide cross-platform support, eliminate inconsistency and effort/time required to support both platforms.

@shurick81, would you put more ideas here, please?

**Comment by avishnyakov** [comment]
Implemented in https://github.com/SubPointSolutions/metabox/issues/98
