### ISSUE TITLE
Sql14Role still points to sql2012sp2

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/metabox#83]
Seems that Sql14Role incorrectly returns path to sql2012sp2 files, something has to do with inheritance in Ruby classes.

That needs to be covered with unit tests to ensure that roles returns correct values.

**Comment by shurick81** [comment]
tested the whole flow, including SQL installing and SP farm spinning: https://github.com/SubPointSolutions/metabox/pull/93

**Comment by SubPointSupport** [comment]
Merged.
