### ISSUE TITLE
Error when spinning up the stack triggers an error

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#84]
Steps to reproduce:
1. cd to `.\src`
2. run `cls && "config/.contoso.bat" && rake resource:generate && rake vagrant:up[contoso16::dc]`

Expected result:
DC with domain up and running.

Outcome:
Error https://gist.github.com/shurick81/ed2a81b7e8bad1938b9678a940f2adca

**Comment by SubPointSupport** [comment]
In progress, fixing that.

**Comment by SubPointSupport** [comment]
Fixed in the recent
