### ISSUE TITLE
Cloning source code - "Repository not found" error

### ISSUE THREAD

**Issue by NZainchkovskiy** [SubPointSolutions/metabox#9]
I'm trying to install metabox.
When I doing "git clone" command according to your documentation, I got "remote: Repository not found" error.

> C:\Metabox>git clone https://github.com/subpointsolutions/metabox-beta.git
Cloning into 'metabox-beta'...
remote: Repository not found.
fatal: repository 'https://github.com/subpointsolutions/metabox-beta.git/' not found

What I am doing wrong?
Thank you!

**Comment by shurick81** [comment]
Thank you, it's a wrong repo address in the documentation.
The correct repo URL is https://github.com/subpointsolutions/metabox.git. I will fix the documentation soon.

**Comment by shurick81** [comment]
Fixed https://github.com/subpointsolutions/metabox/wiki/metabox-installation
