### ISSUE TITLE
Vagrant timed out while attempting to connect via WinRM

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#94]
Steps to reproduce:
1. Install prerequisites and Metabox
2. Run
```
metabox fileset download sql::sql2012sp2
metabox fileset download sp2016::sp2016server_rtm
metabox fileset download sp2016::sp2016_fp2

metabox resource generate && metabox packer build win2016-mb-soe
metabox resource generate && metabox vagrant add win2016-mb-soe --force

metabox resource generate && metabox packer build win2016-mb-app
metabox resource generate && metabox vagrant add win2016-mb-app --force

metabox resource generate && metabox packer build win2016-mb-bin-sp16rtm
metabox resource generate && metabox vagrant add win2016-mb-bin-sp16rtm --force

metabox resource generate && metabox packer build win2016-mb-bin-sp16fp2
metabox resource generate && metabox vagrant add win2016-mb-bin-sp16fp2 --force

metabox resource generate && metabox vagrant up contoso16::dc
metabox resource generate && metabox vagrant up contoso16::sql14
```
3. Finally run
```
metabox resource generate && metabox vagrant up contoso16::sp16_fp2
```

Expected result: SP Farm up and running

Actual outcome: provisioning error:
https://gist.github.com/shurick81/d8e9bfde3c1f4841644657e823985422

after the error when I run `metabox resource generate && metabox vagrant up contoso16::sp16_fp2` it works just fine, on top of existing VM. It can be related to exceptional size of the image or it can be related to the performance of host. I think we should keep this issue for some time and collect some statistics that will help us decide what to do with it.

**Comment by shurick81** [comment]
@avishnyakov , @hndanesh have you encountered such behavior?

**Comment by avishnyakov** [comment]
Looks that VirtualBox sometimes fails to revert default folder. Logs indicate that fail happen while executing `VBoxManage setproperty machinefolder default`. Let's keen an eye on this under CI. Will close this ticket, feel free to add more details if it fails again on `VBoxManage setproperty machinefolder default`
