### ISSUE TITLE
VBoxManage error 0x80004005

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#95]
Steps to reproduce:
1. Install Windows 10 or 2016 with the build 1703 or newer
2. Install Metabox third party tools
3. Start building any image. For example, `metabox resource generate && metabox packer build win2016-mb-soe`

Expected result: compiled image.

Actual outcome: error:
```
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: The virtual machine 'packer-virtualbox-iso-1530706338' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\Administrator\.metabox_home\packer_vms\default\packer-virtualbox-iso-1530706338\Logs\VBoxHardening.log'
==> virtualbox-iso: VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage.exe: error: The virtual machine 'packer-virtualbox-iso-1530706338' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\Administrator\.metabox_home\packer_vms\default\packer-virtualbox-iso-1530706338\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: The virtual machine 'packer-virtualbox-iso-1530706338' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\Administrator\.metabox_home\packer_vms\default\packer-virtualbox-iso-1530706338\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
```

Apparently, older versions of VirtualBox do not well support the newest Windows versions: https://www.virtualbox.org/ticket/16892

**Comment by avishnyakov** [comment]
@shurick81 followed up with the following enhancement

> add "metabox env" to dump OS, packer, vagrant and metabox and other info #97

**Comment by shurick81** [comment]
after a number of tests we can make following conclusions:

1. If we want to release something that works on Windows 10 released 1709, we need to move forward from this VB version.
2. We can use any newer VB version. This will solve the issue.
3. Metabox works just fine with newer VB versions, including the newest 5.2.14, so if we want, we can use that one.

**Comment by avishnyakov** [comment]
@shurick81 what's the way forward? Update VirtualBox version for win install in the bootstrap script?

**Comment by avishnyakov** [comment]
Not on us, that would be more of VirtualBox/Vagrant compatibility. I'd close this because we can't do much here. If Vagrant or Packer does not work without metabox, then it's not on us to fix it.

**Comment by shurick81** [comment]
What we can probably do is just changing vb version in our Windows bootstrap
