### ISSUE TITLE
metabox fails to build win2016-mb-soe image

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#96]
The following cmd fails:

`
metabox resource generate && metabox packer build win2016-mb-soe
`

This happens because original ISO image seems to be moved, and the following link is no longer active:
> http://care.dlservice.microsoft.com/dl/download/1/6/F/16FA20E6-4662-482A-920B-1A45CF5AAE3C/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO

Several things need to be done to fix this:
* [x] introduce `metabox packer cache_list* cmd to show packer cache folder content
* [x] introduce `metabox packer cache_purge* cmd to clean packer cache folder content
* [x] find new ISO url for base win16 image
* [ ] update Jenkins2 CI server with packer cache clean step so that ISo download would happen daily

**Comment by avishnyakov** [comment]
We got lucky. Seems we don't have ability to get ISOs under http://care.dlservice.microsoft.com. Quick registration surfaces the following link for win2016 ISO:
> https://software-download.microsoft.com/download/pr/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO

Looking over github repos:
1) most of the repos are old, refer to care-links which don’t work 
2) found two repos with the updated link

> https://github.com/chef/bento/blob/4d32668d30a268443cd0ccbb52c80695429cb488/windows/2016.json
> https://github.com/447008888/money/blob/fedc5f40be55b5c992099b9f8a507edb103372cc/tools/bento/windows/2016.json

Config looks as following, was updated 2 days ago. Thanks @www3838438  and @tas50
```
"iso_checksum": "772700802951b36c8cb26a61c040b9a8dc3816a3",
"iso_url": "https://software-download.microsoft.com/download/pr/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO",
"template": "windows-2016-standard"
```

Giving a local test, making sure sysprep works and following vagrant builds are ok.

**Comment by shurick81** [comment]
Here is the same ISO as we used before:
```
            "iso_checksum": "18a4f00a675b0338f3c7c93c4f131beb",
            "iso_checksum_type": "md5",
            "iso_url": "https://download.microsoft.com/download/1/6/F/16FA20E6-4662-482A-920B-1A45CF5AAE3C/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO",
```

**Comment by avishnyakov** [comment]
Fixed in integration branch. We now can install from local KB (KB4103720) or use it directly from the internet. Also improved naming convention as mentioned in Consider Vagrant Cloud publishing #50

```
# install from local KB binary
metabox packer build win-2016-datacenter-soe --force
# or stream online
SET "SOE_KB_ONLINE_INSTALL=1" && metabox packer build win-2016-datacenter-soe --force
metabox vagrant add win-2016-datacenter-soe --force

metabox packer build win-2016-datacenter-app --force 
metabox vagrant add win-2016-datacenter-app --force

metabox packer build win-2016-datacenter-sp16bin-rtm --force
metabox vagrant add win-2016-datacenter-sp16bin-rtm --force

metabox packer build win-2016-datacenter-sp16bin-fp2  --force
metabox vagrant add win-2016-datacenter-sp16bin-fp2 --force
```

Vagrant VM testing is in progress, will be following up with a PR once ready.

**Comment by avishnyakov** [comment]
Implemented, closing? @shurick81
